# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: Local

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  CoverageThreshold: 80

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.102'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--no-restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    arguments: '--collect:"XPlat Code Coverage"'

- task: reportgenerator@5
  displayName: ReportGenerator
  inputs:
    reports: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    reporttypes: 'HtmlInline_AzurePipelines_Dark;Cobertura'
    targetdir: 'coveragereport'

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    reportDirectory: 'coveragereport'

- powershell: |
    [xml]$coverage = Get-Content "$(Agent.TempDirectory)/**/coverage.cobertura.xml"
    $lineRate = [double]$coverage.coverage.'line-rate'
    $percent = [math]::Round($lineRate * 100, 2)

    Write-Host "Cobertura atual: $percent%"

    if ($percent -lt $(CoverageThreshold)) {
        Write-Error "Cobertura abaixo do m√≠nimo exigido ($(CoverageThreshold)%)"
    }
  displayName: Quality Gate - Code Coverage